# This is a basic workflow to help you get started with Actions

name: pdf

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
#  pull_request:
#    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Set up Git repository
        uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - uses: SadPencil/texlive-action/full@v2
        with:
          run: |
            # Install fonts
            ( cp -rf depends/font/* /usr/share/fonts/ && fc-cache ) || true
            # Install python3, Java Runtime, graphviz, make
            apt-get update
            apt-get -y install python3 python3-pip default-jre graphviz make
            # Install sphix, sphinxcontrib-plantuml (latest version)
            python3 -m pip install -U setuptools
            python3 -m pip install -U sphinx sphinx-autobuild sphinx_rtd_theme recommonmark sphinx-markdown-tables sphinxcontrib-plantuml
            # Download plantuml.jar
            echo use "depends/plantuml/plantuml.jar"
            # Produce .tex files && Compile to PDF
            make latexpdf
            
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: output.pdf
          path: build/latex/sphinx.pdf
